name: portfolio
description: 'Personal portfolio website developed in flutter'
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.4.1
  flutter_svg: ^2.0.0
  image_network: ^2.6.0
  lint: ^2.0.0
  modular_core: ^3.4.1
  modular_interfaces: ^3.0.0
  percent_indicator: ^4.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Patua One
      fonts:
        - asset: assets/fonts/patua_one/PatuaOne-Regular.ttf
    - family: Baloo 2
      fonts:
        - asset: assets/fonts/baloo_2/Baloo2-Regular.ttf
    - family: Exotc350 Bd BT
      fonts:
        - asset: assets/fonts/exotc350_bd_bt/Exotc350BdBTBold.ttf

